import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { useDispatch } from "react-redux";
import { Container, Grid } from "@mantine/core";
import { useAccount } from "wagmi";
import { useRepoliceGetPolls, useRepolicePolls } from "@/RepoliceABI";
import CreatePollCta from "@/components/CreatePollCTA";
import styled from "styled-components";
import { SEPOLIA_ADDRESS } from "@/domain/Contract";
import { Poll } from "@/components/Poll";

const Island = styled.div`
  display: flex;
  padding: 1rem;
  height: 100vh;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
`;

const Polls = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-wrap: wrap;
  width: 100%;
  gap: 1rem;
`;

const Title = styled.h1`
  color: var(--secondary);
  font-size: 3rem;
  text-align: center;
`;

export default function Home() {
  const dispatch = useDispatch();
  const { address } = useAccount();
  const { data } = useRepoliceGetPolls({ address: SEPOLIA_ADDRESS });

  console.info("Connected Wallet Address", address);
  console.info("useRepoliceGetPolls", data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Container>
          <h1>Repolice - Trustless Polling</h1>

          {/* <HeroSection /> */}

          <Island>
            <CreatePollCta />
            <Polls>
              {data?.map((poll) => (
                <Poll {...poll} />
              ))}
            </Polls>
            {/* <UserStats /> */}
          </Island>

          {/* <HowItWorks /> */}

          {/* <RecentPolls /> */}

          {/* <Faq /> */}

          {/* <Footer /> */}
        </Container>
      </main>
    </>
  );
}
