import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { api } from "@/services/repolice";

import { useDispatch, useSelector } from "react-redux";
import { wrapper } from "@/store/store";
import { Container, Grid } from "@mantine/core";
import HeroSection from "@/components/HeroSection";

const inter = Inter({ subsets: ["latin"] });

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async ({ params }) => {
      // we can set the initial state from here
      // we are setting to false but you can run your custom logic here
      //await store.dispatch(setAuthState(false));
      console.log("State on server", store.getState());
      return {
        props: {
          authState: false,
        },
      };
    }
);

export default function Home() {
  const dispatch = useDispatch();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Container>
          <h1>Repolice: Trustless Polling on Blockchain</h1>

          <HeroSection />

          <Grid>
            <Grid.Col span={8}>{/* <ExplorePolls /> */}</Grid.Col>

            <Grid.Col span={4}>
              {/* <CreatePollCta /> */}
              {/* <UserStats /> */}
            </Grid.Col>
          </Grid>

          {/* <HowItWorks /> */}

          {/* <RecentPolls /> */}

          {/* <Faq /> */}

          {/* <Footer /> */}
        </Container>
      </main>
    </>
  );
}
